Repository UnbloktTechnology/nexeraid-examples, pull requests merged in 2023-10, with the labels that each got.

#142 NEXID-1569 - Added new nexeraid aave pool proxy to address in Mumbai …
  aave_interface/src/ui-config/marketsConfig.tsx
Labels: Don't merge yet

#145 Update readme with offchain zkp url
  readme.md
Labels: ready to review

#150 Fix defi zkp
  defi_zkp_example/src/features/identity/useCheckCompliance.tsx
  defi_zkp_example/src/pages/api/scenario-webhook.ts
  defi_zkp_example/src/pages/index.tsx
  defi_zkp_example/src/server/api/routers/complianceRouter.ts
  package-lock.json
Labels: ready to review, ready to merge

#181 add sygnum bank app
  root-project/.env.example
  root-project/public/icons/price_change_down.svg
  root-project/public/icons/price_change_up.svg
  root-project/public/images/loadingIcon.gif
  root-project/public/images/sygnum.png
  root-project/public/images/sygnum.svg
  root-project/src/env.mjs
  root-project/src/features/sygnum-web3/Components/Button.tsx
  root-project/src/features/sygnum-web3/Components/Icon.tsx
  root-project/src/features/sygnum-web3/Dashboard/Card.tsx
  root-project/src/features/sygnum-web3/Dashboard/Header.tsx
  root-project/src/features/sygnum-web3/Dashboard/Sidebar.tsx
  root-project/src/features/sygnum-web3/Dashboard/Transactions.tsx
  root-project/src/features/sygnum-web3/Dashboard/Transfer.tsx
  root-project/src/features/sygnum-web3/Dashboard/index.tsx
  root-project/src/features/sygnum-web3/Layout/Content.tsx
  root-project/src/features/sygnum-web3/Layout/Footer.tsx
  root-project/src/features/sygnum-web3/Layout/Header.tsx
  root-project/src/features/sygnum-web3/Layout/Layout.tsx
  root-project/src/features/sygnum-web3/Layout/index.ts
  root-project/src/features/sygnum-web3/Modals/CenterModal.tsx
  root-project/src/features/sygnum-web3/Modals/GlobalModals.tsx
  root-project/src/features/sygnum-web3/Modals/useGlobalModals.tsx
  root-project/src/features/sygnum-web3/identity/IdentityClient.ts
  root-project/src/features/sygnum-web3/identity/IdentityVerifyButton.tsx
  root-project/src/features/sygnum-web3/identity/LogOnModal.tsx
  root-project/src/features/sygnum-web3/identity/useCheckSygnumWeb3Compliance.tsx
  root-project/src/features/sygnum-web3/identity/useKycSygnumWeb3Authentication.tsx
  root-project/src/pages/api/sygnum-web3/scenario-webhook.ts
  root-project/src/pages/index.tsx
  root-project/src/pages/sygnum-web3/index.tsx
  root-project/src/server/api/routers/accessRouter.ts
  root-project/src/styles/globals.css
  root-project/tailwind.config.ts
Labels: ready to review

#180 Wait for onSdkReady callback to call isVerified
  aave_interface/package.json
  aave_interface/src/components/NexeraIDInit.tsx
  aave_interface/src/libs/web3-data-provider/Web3Provider.tsx
  aave_interface/src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
  aave_interface/src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
  aave_interface/src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx
  aave_interface/src/modules/dashboard/lists/SupplyButton.tsx
  aave_interface/yarn.lock
Labels: ready to review
